// swift-tools-version: 5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "Bark",
    platforms: [
        .iOS(.v13),
        .macOS(.v12)
    ],
    products: [
        .library(
            name: "Bark",
            targets: ["Bark"]
        ),
    ],
    dependencies: [],
    targets: [
        // The Swift bindings generated by uniffi
        .target(
            name: "Bark",
            dependencies: ["BarkFFI"],
            path: "bindings/swift/Sources/Bark"
        ),

        // The binary XCFramework containing the Rust library
        .binaryTarget(
            name: "BarkFFI",
            // For local testing, use path instead of url
            path: "bindings/swift/build/xcframework/BarkFFI.xcframework"
            // For releases, use:
            // url: "https://gitlab.com/ark-bitcoin/bark-ffi/-/releases/v0.1.0/downloads/BarkFFI.xcframework.zip",
            // checksum: "0000000000000000000000000000000000000000000000000000000000000000"
        )
    ]
)
