plugins {
    id("com.android.library")
    id("org.jetbrains.kotlin.android")
    id("org.jlleitschuh.gradle.ktlint")
    `maven-publish`
    signing
}

android {
    namespace = "tech.second.bark"
    compileSdk = 34

    defaultConfig {
        minSdk = 24
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    sourceSets {
        getByName("main") {
            // Kotlin source files (generated by uniffi-bindgen)
            java.srcDirs("src/main/kotlin")
            // Native libraries (.so files)
            jniLibs.srcDirs("src/main/jniLibs")
        }
    }
}

dependencies {
    implementation("net.java.dev.jna:jna:5.14.0@aar")
    implementation("org.jetbrains.kotlin:kotlin-stdlib:1.9.24")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.1")

    // Testing dependencies
    testImplementation("junit:junit:4.13.2")
    androidTestImplementation("androidx.test.ext:junit:1.1.5")
    androidTestImplementation("androidx.test:runner:1.5.2")
    androidTestImplementation("androidx.test:rules:1.5.0")
}

// ktlint configuration
ktlint {
    android.set(true)
    filter {
        exclude("**/uniffi/**") // Don't lint generated code
    }
}

// Create empty Javadoc JAR for Maven Central compliance
val javadocJar by tasks.registering(Jar::class) {
    archiveClassifier.set("javadoc")
}

// Maven publishing configuration
publishing {
    publications {
        create<MavenPublication>("release") {
            afterEvaluate {
                from(components["release"])
            }

            groupId = "tech.second.bark"
            artifactId = "bark-android"
            version = project.findProperty("VERSION_NAME") as String? ?: "0.1.0-beta.4"

            artifact(javadocJar)

            pom {
                name.set("Bark Android")
                description.set("Bark - Ark Wallet for Bitcoin (Kotlin/Android Bindings)")
                url.set("https://gitlab.com/ark-bitcoin/bark-ffi")

                licenses {
                    license {
                        name.set("CC0-1.0")
                        url.set("https://creativecommons.org/publicdomain/zero/1.0/")
                    }
                }

                developers {
                    developer {
                        id.set("second-tech")
                        name.set("Team Second")
                        email.set("hello@second.tech")
                    }
                }

                scm {
                    url.set("https://gitlab.com/ark-bitcoin/bark-ffi")
                    connection.set("scm:git:git://gitlab.com/ark-bitcoin/bark-ffi.git")
                    developerConnection.set("scm:git:ssh://git@gitlab.com/ark-bitcoin/bark-ffi.git")
                }
            }
        }
    }
}

// Signing configuration (optional, for Maven Central)
// signing {
//     val signingKey = findProperty("SIGNING_KEY") as String?
//     val signingPassword = findProperty("SIGNING_PASSWORD") as String?
//     if (signingKey != null && signingPassword != null) {
//         useInMemoryPgpKeys(signingKey, signingPassword)
//         sign(publishing.publications["release"])
//     }
// }
