name: bark_example
description: Example application demonstrating the Bark package
version: 0.1.0
publish_to: none

environment:
  sdk: "^3.10.0"

dependencies:
  bark:
    path: ../
  path: ^1.9.0
  bdk_dart:
    git:
      url: https://github.com/kumulynja/bdk-dart.git
      ref: bark-ffi-dep
