// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(barkFFI)
import barkFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_bark_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_bark_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureBarkFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * The main Bark wallet interface for Ark operations
 */
public protocol WalletProtocol: AnyObject, Sendable {
    
    /**
     * Get all VTXOs (including spent)
     */
    func allVtxos() throws  -> [Vtxo]
    
    /**
     * Get Ark server info (null if not connected)
     */
    func arkInfo()  -> ArkInfo?
    
    func balance() throws  -> Balance
    
    func bolt11Invoice(amountSats: UInt64) throws  -> LightningInvoice
    
    /**
     * Get claimable lightning receive balance
     */
    func claimableLightningReceiveBalanceSats() throws  -> UInt64
    
    /**
     * Get wallet config
     */
    func config()  -> Config
    
    /**
     * Get VTXOs expiring within threshold blocks
     */
    func getExpiringVtxos(thresholdBlocks: UInt32) throws  -> [Vtxo]
    
    /**
     * Get a specific VTXO by ID
     */
    func getVtxoById(vtxoId: String) throws  -> Vtxo
    
    /**
     * Get VTXOs that should be refreshed
     */
    func getVtxosToRefresh() throws  -> [Vtxo]
    
    func maintenance() throws 
    
    /**
     * Perform maintenance refresh
     */
    func maintenanceRefresh() throws  -> String?
    
    /**
     * Get all wallet movements (transaction history)
     */
    func movements() throws  -> [Movement]
    
    func newAddress() throws  -> String
    
    /**
     * Generate a new address and return it with its index
     */
    func newAddressWithIndex() throws  -> AddressWithIndex
    
    func offboardAll(bitcoinAddress: String) throws  -> OffboardResult
    
    /**
     * Offboard specific VTXOs to a Bitcoin address
     */
    func offboardVtxos(vtxoIds: [String], bitcoinAddress: String) throws  -> String
    
    func payLightningAddress(lightningAddress: String, amountSats: UInt64, comment: String?) throws  -> LightningPaymentResult
    
    func payLightningInvoice(invoice: String, amountSats: UInt64?) throws  -> LightningPaymentResult
    
    /**
     * Peek at an address at a specific index
     */
    func peakAddress(index: UInt32) throws  -> String
    
    /**
     * Get all pending lightning receives
     */
    func pendingLightningReceives() throws  -> [LightningReceiveStatus]
    
    /**
     * Get all pending lightning sends
     */
    func pendingLightningSends() throws  -> [LightningSendStatus]
    
    func properties() throws  -> WalletProperties
    
    /**
     * Refresh specific VTXOs
     */
    func refreshVtxos(vtxoIds: [String]) throws  -> String?
    
    func sendArkoorPayment(arkAddress: String, amountSats: UInt64) throws  -> String
    
    /**
     * Send an onchain payment during a round
     */
    func sendRoundOnchainPayment(address: String, amountSats: UInt64) throws  -> String
    
    /**
     * Get all spendable VTXOs
     */
    func spendableVtxos() throws  -> [Vtxo]
    
    func sync() throws 
    
    func tryClaimAllLightningReceives(wait: Bool) throws 
    
    func vtxos() throws  -> [Vtxo]
    
}
/**
 * The main Bark wallet interface for Ark operations
 */
open class Wallet: WalletProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_bark_ffi_fn_clone_wallet(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        try! rustCall { uniffi_bark_ffi_fn_free_wallet(handle, $0) }
    }

    
    /**
     * Create a new Bark wallet
     */
public static func create(mnemonic: String, config: Config, datadir: String, forceRescan: Bool)throws  -> Wallet  {
    return try  FfiConverterTypeWallet_lift(try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_constructor_wallet_create(
        FfiConverterString.lower(mnemonic),
        FfiConverterTypeConfig_lower(config),
        FfiConverterString.lower(datadir),
        FfiConverterBool.lower(forceRescan),$0
    )
})
}
    
    /**
     * Open an existing Bark wallet
     */
public static func `open`(mnemonic: String, config: Config, datadir: String)throws  -> Wallet  {
    return try  FfiConverterTypeWallet_lift(try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_constructor_wallet_open(
        FfiConverterString.lower(mnemonic),
        FfiConverterTypeConfig_lower(config),
        FfiConverterString.lower(datadir),$0
    )
})
}
    

    
    /**
     * Get all VTXOs (including spent)
     */
open func allVtxos()throws  -> [Vtxo]  {
    return try  FfiConverterSequenceTypeVtxo.lift(try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_method_wallet_all_vtxos(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Get Ark server info (null if not connected)
     */
open func arkInfo() -> ArkInfo?  {
    return try!  FfiConverterOptionTypeArkInfo.lift(try! rustCall() {
    uniffi_bark_ffi_fn_method_wallet_ark_info(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func balance()throws  -> Balance  {
    return try  FfiConverterTypeBalance_lift(try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_method_wallet_balance(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func bolt11Invoice(amountSats: UInt64)throws  -> LightningInvoice  {
    return try  FfiConverterTypeLightningInvoice_lift(try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_method_wallet_bolt11_invoice(
            self.uniffiCloneHandle(),
        FfiConverterUInt64.lower(amountSats),$0
    )
})
}
    
    /**
     * Get claimable lightning receive balance
     */
open func claimableLightningReceiveBalanceSats()throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_method_wallet_claimable_lightning_receive_balance_sats(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Get wallet config
     */
open func config() -> Config  {
    return try!  FfiConverterTypeConfig_lift(try! rustCall() {
    uniffi_bark_ffi_fn_method_wallet_config(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Get VTXOs expiring within threshold blocks
     */
open func getExpiringVtxos(thresholdBlocks: UInt32)throws  -> [Vtxo]  {
    return try  FfiConverterSequenceTypeVtxo.lift(try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_method_wallet_get_expiring_vtxos(
            self.uniffiCloneHandle(),
        FfiConverterUInt32.lower(thresholdBlocks),$0
    )
})
}
    
    /**
     * Get a specific VTXO by ID
     */
open func getVtxoById(vtxoId: String)throws  -> Vtxo  {
    return try  FfiConverterTypeVtxo_lift(try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_method_wallet_get_vtxo_by_id(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(vtxoId),$0
    )
})
}
    
    /**
     * Get VTXOs that should be refreshed
     */
open func getVtxosToRefresh()throws  -> [Vtxo]  {
    return try  FfiConverterSequenceTypeVtxo.lift(try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_method_wallet_get_vtxos_to_refresh(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func maintenance()throws   {try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_method_wallet_maintenance(
            self.uniffiCloneHandle(),$0
    )
}
}
    
    /**
     * Perform maintenance refresh
     */
open func maintenanceRefresh()throws  -> String?  {
    return try  FfiConverterOptionString.lift(try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_method_wallet_maintenance_refresh(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Get all wallet movements (transaction history)
     */
open func movements()throws  -> [Movement]  {
    return try  FfiConverterSequenceTypeMovement.lift(try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_method_wallet_movements(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func newAddress()throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_method_wallet_new_address(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Generate a new address and return it with its index
     */
open func newAddressWithIndex()throws  -> AddressWithIndex  {
    return try  FfiConverterTypeAddressWithIndex_lift(try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_method_wallet_new_address_with_index(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func offboardAll(bitcoinAddress: String)throws  -> OffboardResult  {
    return try  FfiConverterTypeOffboardResult_lift(try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_method_wallet_offboard_all(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(bitcoinAddress),$0
    )
})
}
    
    /**
     * Offboard specific VTXOs to a Bitcoin address
     */
open func offboardVtxos(vtxoIds: [String], bitcoinAddress: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_method_wallet_offboard_vtxos(
            self.uniffiCloneHandle(),
        FfiConverterSequenceString.lower(vtxoIds),
        FfiConverterString.lower(bitcoinAddress),$0
    )
})
}
    
open func payLightningAddress(lightningAddress: String, amountSats: UInt64, comment: String?)throws  -> LightningPaymentResult  {
    return try  FfiConverterTypeLightningPaymentResult_lift(try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_method_wallet_pay_lightning_address(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(lightningAddress),
        FfiConverterUInt64.lower(amountSats),
        FfiConverterOptionString.lower(comment),$0
    )
})
}
    
open func payLightningInvoice(invoice: String, amountSats: UInt64?)throws  -> LightningPaymentResult  {
    return try  FfiConverterTypeLightningPaymentResult_lift(try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_method_wallet_pay_lightning_invoice(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(invoice),
        FfiConverterOptionUInt64.lower(amountSats),$0
    )
})
}
    
    /**
     * Peek at an address at a specific index
     */
open func peakAddress(index: UInt32)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_method_wallet_peak_address(
            self.uniffiCloneHandle(),
        FfiConverterUInt32.lower(index),$0
    )
})
}
    
    /**
     * Get all pending lightning receives
     */
open func pendingLightningReceives()throws  -> [LightningReceiveStatus]  {
    return try  FfiConverterSequenceTypeLightningReceiveStatus.lift(try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_method_wallet_pending_lightning_receives(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Get all pending lightning sends
     */
open func pendingLightningSends()throws  -> [LightningSendStatus]  {
    return try  FfiConverterSequenceTypeLightningSendStatus.lift(try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_method_wallet_pending_lightning_sends(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func properties()throws  -> WalletProperties  {
    return try  FfiConverterTypeWalletProperties_lift(try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_method_wallet_properties(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Refresh specific VTXOs
     */
open func refreshVtxos(vtxoIds: [String])throws  -> String?  {
    return try  FfiConverterOptionString.lift(try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_method_wallet_refresh_vtxos(
            self.uniffiCloneHandle(),
        FfiConverterSequenceString.lower(vtxoIds),$0
    )
})
}
    
open func sendArkoorPayment(arkAddress: String, amountSats: UInt64)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_method_wallet_send_arkoor_payment(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(arkAddress),
        FfiConverterUInt64.lower(amountSats),$0
    )
})
}
    
    /**
     * Send an onchain payment during a round
     */
open func sendRoundOnchainPayment(address: String, amountSats: UInt64)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_method_wallet_send_round_onchain_payment(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(address),
        FfiConverterUInt64.lower(amountSats),$0
    )
})
}
    
    /**
     * Get all spendable VTXOs
     */
open func spendableVtxos()throws  -> [Vtxo]  {
    return try  FfiConverterSequenceTypeVtxo.lift(try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_method_wallet_spendable_vtxos(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func sync()throws   {try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_method_wallet_sync(
            self.uniffiCloneHandle(),$0
    )
}
}
    
open func tryClaimAllLightningReceives(wait: Bool)throws   {try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_method_wallet_try_claim_all_lightning_receives(
            self.uniffiCloneHandle(),
        FfiConverterBool.lower(wait),$0
    )
}
}
    
open func vtxos()throws  -> [Vtxo]  {
    return try  FfiConverterSequenceTypeVtxo.lift(try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_method_wallet_vtxos(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWallet: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = Wallet

    public static func lift(_ handle: UInt64) throws -> Wallet {
        return Wallet(unsafeFromHandle: handle)
    }

    public static func lower(_ value: Wallet) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Wallet {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: Wallet, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWallet_lift(_ handle: UInt64) throws -> Wallet {
    return try FfiConverterTypeWallet.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWallet_lower(_ value: Wallet) -> UInt64 {
    return FfiConverterTypeWallet.lower(value)
}




/**
 * An Ark address with its derivation index
 */
public struct AddressWithIndex: Equatable, Hashable {
    /**
     * The Ark address string
     */
    public var address: String
    /**
     * The derivation index
     */
    public var index: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The Ark address string
         */address: String, 
        /**
         * The derivation index
         */index: UInt32) {
        self.address = address
        self.index = index
    }

    
}

#if compiler(>=6)
extension AddressWithIndex: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAddressWithIndex: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AddressWithIndex {
        return
            try AddressWithIndex(
                address: FfiConverterString.read(from: &buf), 
                index: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: AddressWithIndex, into buf: inout [UInt8]) {
        FfiConverterString.write(value.address, into: &buf)
        FfiConverterUInt32.write(value.index, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAddressWithIndex_lift(_ buf: RustBuffer) throws -> AddressWithIndex {
    return try FfiConverterTypeAddressWithIndex.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAddressWithIndex_lower(_ value: AddressWithIndex) -> RustBuffer {
    return FfiConverterTypeAddressWithIndex.lower(value)
}


/**
 * Ark server configuration information
 */
public struct ArkInfo: Equatable, Hashable {
    /**
     * The bitcoin network the server operates on
     */
    public var network: Network
    /**
     * The Ark server pubkey as hex string
     */
    public var serverPubkey: String
    /**
     * The interval between each round in seconds
     */
    public var roundIntervalSecs: UInt64
    /**
     * Number of nonces per round
     */
    public var nbRoundNonces: UInt32
    /**
     * Delta between exit confirmation and coins becoming spendable
     */
    public var vtxoExitDelta: UInt32
    /**
     * Expiration delta of the VTXO
     */
    public var vtxoExpiryDelta: UInt32
    /**
     * The number of blocks after which an HTLC-send VTXO expires once granted
     */
    public var htlcSendExpiryDelta: UInt32
    /**
     * The number of blocks to keep between Lightning and Ark HTLCs expiries
     */
    public var htlcExpiryDelta: UInt32
    /**
     * Maximum amount of a VTXO in sats (null if no limit)
     */
    public var maxVtxoAmountSats: UInt64?
    /**
     * The number of confirmations required to register a board vtxo
     */
    public var requiredBoardConfirmations: UInt32
    /**
     * Maximum CLTV delta server will allow clients to request an invoice generation with
     */
    public var maxUserInvoiceCltvDelta: UInt16
    /**
     * Minimum amount for a board the server will cosign in sats
     */
    public var minBoardAmountSats: UInt64
    /**
     * Offboard fee rate in sats per vbyte
     */
    public var offboardFeerateSatPerVb: UInt64
    /**
     * Whether the Ark server requires anti-DoS measures for lightning receives
     */
    public var lnReceiveAntiDosRequired: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The bitcoin network the server operates on
         */network: Network, 
        /**
         * The Ark server pubkey as hex string
         */serverPubkey: String, 
        /**
         * The interval between each round in seconds
         */roundIntervalSecs: UInt64, 
        /**
         * Number of nonces per round
         */nbRoundNonces: UInt32, 
        /**
         * Delta between exit confirmation and coins becoming spendable
         */vtxoExitDelta: UInt32, 
        /**
         * Expiration delta of the VTXO
         */vtxoExpiryDelta: UInt32, 
        /**
         * The number of blocks after which an HTLC-send VTXO expires once granted
         */htlcSendExpiryDelta: UInt32, 
        /**
         * The number of blocks to keep between Lightning and Ark HTLCs expiries
         */htlcExpiryDelta: UInt32, 
        /**
         * Maximum amount of a VTXO in sats (null if no limit)
         */maxVtxoAmountSats: UInt64?, 
        /**
         * The number of confirmations required to register a board vtxo
         */requiredBoardConfirmations: UInt32, 
        /**
         * Maximum CLTV delta server will allow clients to request an invoice generation with
         */maxUserInvoiceCltvDelta: UInt16, 
        /**
         * Minimum amount for a board the server will cosign in sats
         */minBoardAmountSats: UInt64, 
        /**
         * Offboard fee rate in sats per vbyte
         */offboardFeerateSatPerVb: UInt64, 
        /**
         * Whether the Ark server requires anti-DoS measures for lightning receives
         */lnReceiveAntiDosRequired: Bool) {
        self.network = network
        self.serverPubkey = serverPubkey
        self.roundIntervalSecs = roundIntervalSecs
        self.nbRoundNonces = nbRoundNonces
        self.vtxoExitDelta = vtxoExitDelta
        self.vtxoExpiryDelta = vtxoExpiryDelta
        self.htlcSendExpiryDelta = htlcSendExpiryDelta
        self.htlcExpiryDelta = htlcExpiryDelta
        self.maxVtxoAmountSats = maxVtxoAmountSats
        self.requiredBoardConfirmations = requiredBoardConfirmations
        self.maxUserInvoiceCltvDelta = maxUserInvoiceCltvDelta
        self.minBoardAmountSats = minBoardAmountSats
        self.offboardFeerateSatPerVb = offboardFeerateSatPerVb
        self.lnReceiveAntiDosRequired = lnReceiveAntiDosRequired
    }

    
}

#if compiler(>=6)
extension ArkInfo: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeArkInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ArkInfo {
        return
            try ArkInfo(
                network: FfiConverterTypeNetwork.read(from: &buf), 
                serverPubkey: FfiConverterString.read(from: &buf), 
                roundIntervalSecs: FfiConverterUInt64.read(from: &buf), 
                nbRoundNonces: FfiConverterUInt32.read(from: &buf), 
                vtxoExitDelta: FfiConverterUInt32.read(from: &buf), 
                vtxoExpiryDelta: FfiConverterUInt32.read(from: &buf), 
                htlcSendExpiryDelta: FfiConverterUInt32.read(from: &buf), 
                htlcExpiryDelta: FfiConverterUInt32.read(from: &buf), 
                maxVtxoAmountSats: FfiConverterOptionUInt64.read(from: &buf), 
                requiredBoardConfirmations: FfiConverterUInt32.read(from: &buf), 
                maxUserInvoiceCltvDelta: FfiConverterUInt16.read(from: &buf), 
                minBoardAmountSats: FfiConverterUInt64.read(from: &buf), 
                offboardFeerateSatPerVb: FfiConverterUInt64.read(from: &buf), 
                lnReceiveAntiDosRequired: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: ArkInfo, into buf: inout [UInt8]) {
        FfiConverterTypeNetwork.write(value.network, into: &buf)
        FfiConverterString.write(value.serverPubkey, into: &buf)
        FfiConverterUInt64.write(value.roundIntervalSecs, into: &buf)
        FfiConverterUInt32.write(value.nbRoundNonces, into: &buf)
        FfiConverterUInt32.write(value.vtxoExitDelta, into: &buf)
        FfiConverterUInt32.write(value.vtxoExpiryDelta, into: &buf)
        FfiConverterUInt32.write(value.htlcSendExpiryDelta, into: &buf)
        FfiConverterUInt32.write(value.htlcExpiryDelta, into: &buf)
        FfiConverterOptionUInt64.write(value.maxVtxoAmountSats, into: &buf)
        FfiConverterUInt32.write(value.requiredBoardConfirmations, into: &buf)
        FfiConverterUInt16.write(value.maxUserInvoiceCltvDelta, into: &buf)
        FfiConverterUInt64.write(value.minBoardAmountSats, into: &buf)
        FfiConverterUInt64.write(value.offboardFeerateSatPerVb, into: &buf)
        FfiConverterBool.write(value.lnReceiveAntiDosRequired, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeArkInfo_lift(_ buf: RustBuffer) throws -> ArkInfo {
    return try FfiConverterTypeArkInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeArkInfo_lower(_ value: ArkInfo) -> RustBuffer {
    return FfiConverterTypeArkInfo.lower(value)
}


/**
 * Detailed balance breakdown of the wallet
 */
public struct Balance: Equatable, Hashable {
    /**
     * Spendable off-chain balance (Ark) in sats
     */
    public var spendableSats: UInt64
    /**
     * Coins locked in a round
     */
    public var pendingInRoundSats: UInt64
    /**
     * Coins being unilaterally exited
     */
    public var pendingExitSats: UInt64
    /**
     * Coins pending as Lightning sends
     */
    public var pendingLightningSendSats: UInt64
    /**
     * Total pending Lightning receives (all invoices)
     */
    public var pendingLightningReceiveTotalSats: UInt64
    /**
     * Claimable pending Lightning receives
     */
    public var pendingLightningReceiveClaimableSats: UInt64
    /**
     * Coins pending board confirmations
     */
    public var pendingBoardSats: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Spendable off-chain balance (Ark) in sats
         */spendableSats: UInt64, 
        /**
         * Coins locked in a round
         */pendingInRoundSats: UInt64, 
        /**
         * Coins being unilaterally exited
         */pendingExitSats: UInt64, 
        /**
         * Coins pending as Lightning sends
         */pendingLightningSendSats: UInt64, 
        /**
         * Total pending Lightning receives (all invoices)
         */pendingLightningReceiveTotalSats: UInt64, 
        /**
         * Claimable pending Lightning receives
         */pendingLightningReceiveClaimableSats: UInt64, 
        /**
         * Coins pending board confirmations
         */pendingBoardSats: UInt64) {
        self.spendableSats = spendableSats
        self.pendingInRoundSats = pendingInRoundSats
        self.pendingExitSats = pendingExitSats
        self.pendingLightningSendSats = pendingLightningSendSats
        self.pendingLightningReceiveTotalSats = pendingLightningReceiveTotalSats
        self.pendingLightningReceiveClaimableSats = pendingLightningReceiveClaimableSats
        self.pendingBoardSats = pendingBoardSats
    }

    
}

#if compiler(>=6)
extension Balance: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBalance: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Balance {
        return
            try Balance(
                spendableSats: FfiConverterUInt64.read(from: &buf), 
                pendingInRoundSats: FfiConverterUInt64.read(from: &buf), 
                pendingExitSats: FfiConverterUInt64.read(from: &buf), 
                pendingLightningSendSats: FfiConverterUInt64.read(from: &buf), 
                pendingLightningReceiveTotalSats: FfiConverterUInt64.read(from: &buf), 
                pendingLightningReceiveClaimableSats: FfiConverterUInt64.read(from: &buf), 
                pendingBoardSats: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: Balance, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.spendableSats, into: &buf)
        FfiConverterUInt64.write(value.pendingInRoundSats, into: &buf)
        FfiConverterUInt64.write(value.pendingExitSats, into: &buf)
        FfiConverterUInt64.write(value.pendingLightningSendSats, into: &buf)
        FfiConverterUInt64.write(value.pendingLightningReceiveTotalSats, into: &buf)
        FfiConverterUInt64.write(value.pendingLightningReceiveClaimableSats, into: &buf)
        FfiConverterUInt64.write(value.pendingBoardSats, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBalance_lift(_ buf: RustBuffer) throws -> Balance {
    return try FfiConverterTypeBalance.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBalance_lower(_ value: Balance) -> RustBuffer {
    return FfiConverterTypeBalance.lower(value)
}


/**
 * Configuration for creating/opening a Bark wallet
 */
public struct Config: Equatable, Hashable {
    /**
     * Ark server address
     */
    public var serverAddress: String
    /**
     * Esplora HTTP REST server address
     */
    public var esploraAddress: String?
    /**
     * Bitcoind RPC server address
     */
    public var bitcoindAddress: String?
    /**
     * Bitcoind RPC cookie file path
     */
    public var bitcoindCookiefile: String?
    /**
     * Bitcoind RPC username
     */
    public var bitcoindUser: String?
    /**
     * Bitcoind RPC password
     */
    public var bitcoindPass: String?
    /**
     * Bitcoin network
     */
    public var network: Network
    /**
     * Number of blocks before expiration to refresh VTXOs
     */
    public var vtxoRefreshExpiryThreshold: UInt32?
    /**
     * Upper limit of blocks needed to safely exit VTXOs
     */
    public var vtxoExitMargin: UInt16?
    /**
     * Number of blocks to claim a HTLC-recv VTXO
     */
    public var htlcRecvClaimDelta: UInt16?
    /**
     * Fallback fee rate in sat/kWu
     */
    public var fallbackFeeRate: UInt64?
    /**
     * Confirmations required before considering a round tx fully confirmed
     */
    public var roundTxRequiredConfirmations: UInt32?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Ark server address
         */serverAddress: String, 
        /**
         * Esplora HTTP REST server address
         */esploraAddress: String?, 
        /**
         * Bitcoind RPC server address
         */bitcoindAddress: String?, 
        /**
         * Bitcoind RPC cookie file path
         */bitcoindCookiefile: String?, 
        /**
         * Bitcoind RPC username
         */bitcoindUser: String?, 
        /**
         * Bitcoind RPC password
         */bitcoindPass: String?, 
        /**
         * Bitcoin network
         */network: Network, 
        /**
         * Number of blocks before expiration to refresh VTXOs
         */vtxoRefreshExpiryThreshold: UInt32?, 
        /**
         * Upper limit of blocks needed to safely exit VTXOs
         */vtxoExitMargin: UInt16?, 
        /**
         * Number of blocks to claim a HTLC-recv VTXO
         */htlcRecvClaimDelta: UInt16?, 
        /**
         * Fallback fee rate in sat/kWu
         */fallbackFeeRate: UInt64?, 
        /**
         * Confirmations required before considering a round tx fully confirmed
         */roundTxRequiredConfirmations: UInt32?) {
        self.serverAddress = serverAddress
        self.esploraAddress = esploraAddress
        self.bitcoindAddress = bitcoindAddress
        self.bitcoindCookiefile = bitcoindCookiefile
        self.bitcoindUser = bitcoindUser
        self.bitcoindPass = bitcoindPass
        self.network = network
        self.vtxoRefreshExpiryThreshold = vtxoRefreshExpiryThreshold
        self.vtxoExitMargin = vtxoExitMargin
        self.htlcRecvClaimDelta = htlcRecvClaimDelta
        self.fallbackFeeRate = fallbackFeeRate
        self.roundTxRequiredConfirmations = roundTxRequiredConfirmations
    }

    
}

#if compiler(>=6)
extension Config: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Config {
        return
            try Config(
                serverAddress: FfiConverterString.read(from: &buf), 
                esploraAddress: FfiConverterOptionString.read(from: &buf), 
                bitcoindAddress: FfiConverterOptionString.read(from: &buf), 
                bitcoindCookiefile: FfiConverterOptionString.read(from: &buf), 
                bitcoindUser: FfiConverterOptionString.read(from: &buf), 
                bitcoindPass: FfiConverterOptionString.read(from: &buf), 
                network: FfiConverterTypeNetwork.read(from: &buf), 
                vtxoRefreshExpiryThreshold: FfiConverterOptionUInt32.read(from: &buf), 
                vtxoExitMargin: FfiConverterOptionUInt16.read(from: &buf), 
                htlcRecvClaimDelta: FfiConverterOptionUInt16.read(from: &buf), 
                fallbackFeeRate: FfiConverterOptionUInt64.read(from: &buf), 
                roundTxRequiredConfirmations: FfiConverterOptionUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: Config, into buf: inout [UInt8]) {
        FfiConverterString.write(value.serverAddress, into: &buf)
        FfiConverterOptionString.write(value.esploraAddress, into: &buf)
        FfiConverterOptionString.write(value.bitcoindAddress, into: &buf)
        FfiConverterOptionString.write(value.bitcoindCookiefile, into: &buf)
        FfiConverterOptionString.write(value.bitcoindUser, into: &buf)
        FfiConverterOptionString.write(value.bitcoindPass, into: &buf)
        FfiConverterTypeNetwork.write(value.network, into: &buf)
        FfiConverterOptionUInt32.write(value.vtxoRefreshExpiryThreshold, into: &buf)
        FfiConverterOptionUInt16.write(value.vtxoExitMargin, into: &buf)
        FfiConverterOptionUInt16.write(value.htlcRecvClaimDelta, into: &buf)
        FfiConverterOptionUInt64.write(value.fallbackFeeRate, into: &buf)
        FfiConverterOptionUInt32.write(value.roundTxRequiredConfirmations, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConfig_lift(_ buf: RustBuffer) throws -> Config {
    return try FfiConverterTypeConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeConfig_lower(_ value: Config) -> RustBuffer {
    return FfiConverterTypeConfig.lower(value)
}


/**
 * Result of creating a BOLT11 invoice
 */
public struct LightningInvoice: Equatable, Hashable {
    /**
     * The BOLT11 invoice string
     */
    public var invoice: String
    /**
     * Amount in sats
     */
    public var amountSats: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The BOLT11 invoice string
         */invoice: String, 
        /**
         * Amount in sats
         */amountSats: UInt64) {
        self.invoice = invoice
        self.amountSats = amountSats
    }

    
}

#if compiler(>=6)
extension LightningInvoice: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLightningInvoice: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LightningInvoice {
        return
            try LightningInvoice(
                invoice: FfiConverterString.read(from: &buf), 
                amountSats: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: LightningInvoice, into buf: inout [UInt8]) {
        FfiConverterString.write(value.invoice, into: &buf)
        FfiConverterUInt64.write(value.amountSats, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLightningInvoice_lift(_ buf: RustBuffer) throws -> LightningInvoice {
    return try FfiConverterTypeLightningInvoice.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLightningInvoice_lower(_ value: LightningInvoice) -> RustBuffer {
    return FfiConverterTypeLightningInvoice.lower(value)
}


/**
 * Result of a successful lightning payment
 */
public struct LightningPaymentResult: Equatable, Hashable {
    /**
     * The invoice that was paid
     */
    public var invoice: String
    /**
     * Payment preimage as hex string
     */
    public var preimage: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The invoice that was paid
         */invoice: String, 
        /**
         * Payment preimage as hex string
         */preimage: String) {
        self.invoice = invoice
        self.preimage = preimage
    }

    
}

#if compiler(>=6)
extension LightningPaymentResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLightningPaymentResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LightningPaymentResult {
        return
            try LightningPaymentResult(
                invoice: FfiConverterString.read(from: &buf), 
                preimage: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: LightningPaymentResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.invoice, into: &buf)
        FfiConverterString.write(value.preimage, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLightningPaymentResult_lift(_ buf: RustBuffer) throws -> LightningPaymentResult {
    return try FfiConverterTypeLightningPaymentResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLightningPaymentResult_lower(_ value: LightningPaymentResult) -> RustBuffer {
    return FfiConverterTypeLightningPaymentResult.lower(value)
}


/**
 * Status of a pending Lightning receive
 */
public struct LightningReceiveStatus: Equatable, Hashable {
    /**
     * Payment hash
     */
    public var paymentHash: String
    /**
     * The BOLT11 invoice
     */
    public var invoice: String
    /**
     * Amount in sats
     */
    public var amountSats: UInt64
    /**
     * Whether HTLC VTXOs have been received
     */
    public var hasHtlcVtxos: Bool
    /**
     * Whether preimage has been revealed
     */
    public var preimageRevealed: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Payment hash
         */paymentHash: String, 
        /**
         * The BOLT11 invoice
         */invoice: String, 
        /**
         * Amount in sats
         */amountSats: UInt64, 
        /**
         * Whether HTLC VTXOs have been received
         */hasHtlcVtxos: Bool, 
        /**
         * Whether preimage has been revealed
         */preimageRevealed: Bool) {
        self.paymentHash = paymentHash
        self.invoice = invoice
        self.amountSats = amountSats
        self.hasHtlcVtxos = hasHtlcVtxos
        self.preimageRevealed = preimageRevealed
    }

    
}

#if compiler(>=6)
extension LightningReceiveStatus: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLightningReceiveStatus: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LightningReceiveStatus {
        return
            try LightningReceiveStatus(
                paymentHash: FfiConverterString.read(from: &buf), 
                invoice: FfiConverterString.read(from: &buf), 
                amountSats: FfiConverterUInt64.read(from: &buf), 
                hasHtlcVtxos: FfiConverterBool.read(from: &buf), 
                preimageRevealed: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: LightningReceiveStatus, into buf: inout [UInt8]) {
        FfiConverterString.write(value.paymentHash, into: &buf)
        FfiConverterString.write(value.invoice, into: &buf)
        FfiConverterUInt64.write(value.amountSats, into: &buf)
        FfiConverterBool.write(value.hasHtlcVtxos, into: &buf)
        FfiConverterBool.write(value.preimageRevealed, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLightningReceiveStatus_lift(_ buf: RustBuffer) throws -> LightningReceiveStatus {
    return try FfiConverterTypeLightningReceiveStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLightningReceiveStatus_lower(_ value: LightningReceiveStatus) -> RustBuffer {
    return FfiConverterTypeLightningReceiveStatus.lower(value)
}


/**
 * Status of a pending Lightning send
 */
public struct LightningSendStatus: Equatable, Hashable {
    /**
     * The invoice being paid
     */
    public var invoice: String
    /**
     * Amount in sats
     */
    public var amountSats: UInt64
    /**
     * Number of HTLC VTXOs locked
     */
    public var htlcVtxoCount: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The invoice being paid
         */invoice: String, 
        /**
         * Amount in sats
         */amountSats: UInt64, 
        /**
         * Number of HTLC VTXOs locked
         */htlcVtxoCount: UInt32) {
        self.invoice = invoice
        self.amountSats = amountSats
        self.htlcVtxoCount = htlcVtxoCount
    }

    
}

#if compiler(>=6)
extension LightningSendStatus: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLightningSendStatus: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LightningSendStatus {
        return
            try LightningSendStatus(
                invoice: FfiConverterString.read(from: &buf), 
                amountSats: FfiConverterUInt64.read(from: &buf), 
                htlcVtxoCount: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: LightningSendStatus, into buf: inout [UInt8]) {
        FfiConverterString.write(value.invoice, into: &buf)
        FfiConverterUInt64.write(value.amountSats, into: &buf)
        FfiConverterUInt32.write(value.htlcVtxoCount, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLightningSendStatus_lift(_ buf: RustBuffer) throws -> LightningSendStatus {
    return try FfiConverterTypeLightningSendStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLightningSendStatus_lower(_ value: LightningSendStatus) -> RustBuffer {
    return FfiConverterTypeLightningSendStatus.lower(value)
}


/**
 * Wallet movement/transaction record
 */
public struct Movement: Equatable, Hashable {
    /**
     * Movement ID
     */
    public var id: UInt32
    /**
     * Status (pending, finished, failed, cancelled)
     */
    public var status: String
    /**
     * Subsystem name
     */
    public var subsystemName: String
    /**
     * Subsystem kind
     */
    public var subsystemKind: String
    /**
     * Metadata as JSON string
     */
    public var metadataJson: String
    /**
     * Intended balance change in sats
     */
    public var intendedBalanceSats: Int64
    /**
     * Effective balance change in sats
     */
    public var effectiveBalanceSats: Int64
    /**
     * Offchain fee in sats
     */
    public var offchainFeeSats: UInt64
    /**
     * Addresses/invoices sent to
     */
    public var sentToAddresses: [String]
    /**
     * Addresses/invoices received on
     */
    public var receivedOnAddresses: [String]
    /**
     * Input VTXO IDs
     */
    public var inputVtxoIds: [String]
    /**
     * Output VTXO IDs
     */
    public var outputVtxoIds: [String]
    /**
     * Created at timestamp
     */
    public var createdAt: String
    /**
     * Updated at timestamp
     */
    public var updatedAt: String
    /**
     * Completed at timestamp (null if not completed)
     */
    public var completedAt: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Movement ID
         */id: UInt32, 
        /**
         * Status (pending, finished, failed, cancelled)
         */status: String, 
        /**
         * Subsystem name
         */subsystemName: String, 
        /**
         * Subsystem kind
         */subsystemKind: String, 
        /**
         * Metadata as JSON string
         */metadataJson: String, 
        /**
         * Intended balance change in sats
         */intendedBalanceSats: Int64, 
        /**
         * Effective balance change in sats
         */effectiveBalanceSats: Int64, 
        /**
         * Offchain fee in sats
         */offchainFeeSats: UInt64, 
        /**
         * Addresses/invoices sent to
         */sentToAddresses: [String], 
        /**
         * Addresses/invoices received on
         */receivedOnAddresses: [String], 
        /**
         * Input VTXO IDs
         */inputVtxoIds: [String], 
        /**
         * Output VTXO IDs
         */outputVtxoIds: [String], 
        /**
         * Created at timestamp
         */createdAt: String, 
        /**
         * Updated at timestamp
         */updatedAt: String, 
        /**
         * Completed at timestamp (null if not completed)
         */completedAt: String?) {
        self.id = id
        self.status = status
        self.subsystemName = subsystemName
        self.subsystemKind = subsystemKind
        self.metadataJson = metadataJson
        self.intendedBalanceSats = intendedBalanceSats
        self.effectiveBalanceSats = effectiveBalanceSats
        self.offchainFeeSats = offchainFeeSats
        self.sentToAddresses = sentToAddresses
        self.receivedOnAddresses = receivedOnAddresses
        self.inputVtxoIds = inputVtxoIds
        self.outputVtxoIds = outputVtxoIds
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.completedAt = completedAt
    }

    
}

#if compiler(>=6)
extension Movement: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMovement: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Movement {
        return
            try Movement(
                id: FfiConverterUInt32.read(from: &buf), 
                status: FfiConverterString.read(from: &buf), 
                subsystemName: FfiConverterString.read(from: &buf), 
                subsystemKind: FfiConverterString.read(from: &buf), 
                metadataJson: FfiConverterString.read(from: &buf), 
                intendedBalanceSats: FfiConverterInt64.read(from: &buf), 
                effectiveBalanceSats: FfiConverterInt64.read(from: &buf), 
                offchainFeeSats: FfiConverterUInt64.read(from: &buf), 
                sentToAddresses: FfiConverterSequenceString.read(from: &buf), 
                receivedOnAddresses: FfiConverterSequenceString.read(from: &buf), 
                inputVtxoIds: FfiConverterSequenceString.read(from: &buf), 
                outputVtxoIds: FfiConverterSequenceString.read(from: &buf), 
                createdAt: FfiConverterString.read(from: &buf), 
                updatedAt: FfiConverterString.read(from: &buf), 
                completedAt: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: Movement, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.id, into: &buf)
        FfiConverterString.write(value.status, into: &buf)
        FfiConverterString.write(value.subsystemName, into: &buf)
        FfiConverterString.write(value.subsystemKind, into: &buf)
        FfiConverterString.write(value.metadataJson, into: &buf)
        FfiConverterInt64.write(value.intendedBalanceSats, into: &buf)
        FfiConverterInt64.write(value.effectiveBalanceSats, into: &buf)
        FfiConverterUInt64.write(value.offchainFeeSats, into: &buf)
        FfiConverterSequenceString.write(value.sentToAddresses, into: &buf)
        FfiConverterSequenceString.write(value.receivedOnAddresses, into: &buf)
        FfiConverterSequenceString.write(value.inputVtxoIds, into: &buf)
        FfiConverterSequenceString.write(value.outputVtxoIds, into: &buf)
        FfiConverterString.write(value.createdAt, into: &buf)
        FfiConverterString.write(value.updatedAt, into: &buf)
        FfiConverterOptionString.write(value.completedAt, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMovement_lift(_ buf: RustBuffer) throws -> Movement {
    return try FfiConverterTypeMovement.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMovement_lower(_ value: Movement) -> RustBuffer {
    return FfiConverterTypeMovement.lower(value)
}


/**
 * Result of an offboard operation
 */
public struct OffboardResult: Equatable, Hashable {
    /**
     * The round ID
     */
    public var roundId: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * The round ID
         */roundId: String) {
        self.roundId = roundId
    }

    
}

#if compiler(>=6)
extension OffboardResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeOffboardResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> OffboardResult {
        return
            try OffboardResult(
                roundId: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: OffboardResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.roundId, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOffboardResult_lift(_ buf: RustBuffer) throws -> OffboardResult {
    return try FfiConverterTypeOffboardResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeOffboardResult_lower(_ value: OffboardResult) -> RustBuffer {
    return FfiConverterTypeOffboardResult.lower(value)
}


/**
 * Simplified view of a VTXO
 */
public struct Vtxo: Equatable, Hashable {
    /**
     * VTXO id like "686...9aa:0"
     */
    public var id: String
    /**
     * Amount in sats
     */
    public var amountSats: UInt64
    /**
     * Expiry height (0 if unknown)
     */
    public var expiryHeight: UInt32
    /**
     * Type of VTXO (e.g., "board", "round", "arkoor")
     */
    public var kind: String
    /**
     * State of VTXO (e.g., "spendable", "spent", "locked")
     */
    public var state: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * VTXO id like "686...9aa:0"
         */id: String, 
        /**
         * Amount in sats
         */amountSats: UInt64, 
        /**
         * Expiry height (0 if unknown)
         */expiryHeight: UInt32, 
        /**
         * Type of VTXO (e.g., "board", "round", "arkoor")
         */kind: String, 
        /**
         * State of VTXO (e.g., "spendable", "spent", "locked")
         */state: String) {
        self.id = id
        self.amountSats = amountSats
        self.expiryHeight = expiryHeight
        self.kind = kind
        self.state = state
    }

    
}

#if compiler(>=6)
extension Vtxo: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVtxo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Vtxo {
        return
            try Vtxo(
                id: FfiConverterString.read(from: &buf), 
                amountSats: FfiConverterUInt64.read(from: &buf), 
                expiryHeight: FfiConverterUInt32.read(from: &buf), 
                kind: FfiConverterString.read(from: &buf), 
                state: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Vtxo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterUInt64.write(value.amountSats, into: &buf)
        FfiConverterUInt32.write(value.expiryHeight, into: &buf)
        FfiConverterString.write(value.kind, into: &buf)
        FfiConverterString.write(value.state, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVtxo_lift(_ buf: RustBuffer) throws -> Vtxo {
    return try FfiConverterTypeVtxo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVtxo_lower(_ value: Vtxo) -> RustBuffer {
    return FfiConverterTypeVtxo.lower(value)
}


/**
 * Read-only properties of the wallet
 */
public struct WalletProperties: Equatable, Hashable {
    public var network: Network
    public var fingerprint: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(network: Network, fingerprint: String) {
        self.network = network
        self.fingerprint = fingerprint
    }

    
}

#if compiler(>=6)
extension WalletProperties: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWalletProperties: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WalletProperties {
        return
            try WalletProperties(
                network: FfiConverterTypeNetwork.read(from: &buf), 
                fingerprint: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: WalletProperties, into buf: inout [UInt8]) {
        FfiConverterTypeNetwork.write(value.network, into: &buf)
        FfiConverterString.write(value.fingerprint, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWalletProperties_lift(_ buf: RustBuffer) throws -> WalletProperties {
    return try FfiConverterTypeWalletProperties.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWalletProperties_lower(_ value: WalletProperties) -> RustBuffer {
    return FfiConverterTypeWalletProperties.lower(value)
}


/**
 * Error types that can occur when using the Bark wallet
 */
public enum BarkError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case Network(message: String
    )
    case Database(message: String
    )
    case InvalidMnemonic(message: String
    )
    case InvalidAddress(message: String
    )
    case InvalidInvoice(message: String
    )
    case InsufficientFunds(message: String
    )
    case NotFound(message: String
    )
    case ServerConnection(message: String
    )
    case Internal(message: String
    )

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension BarkError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBarkError: FfiConverterRustBuffer {
    typealias SwiftType = BarkError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> BarkError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Network(
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .Database(
            message: try FfiConverterString.read(from: &buf)
            )
        case 3: return .InvalidMnemonic(
            message: try FfiConverterString.read(from: &buf)
            )
        case 4: return .InvalidAddress(
            message: try FfiConverterString.read(from: &buf)
            )
        case 5: return .InvalidInvoice(
            message: try FfiConverterString.read(from: &buf)
            )
        case 6: return .InsufficientFunds(
            message: try FfiConverterString.read(from: &buf)
            )
        case 7: return .NotFound(
            message: try FfiConverterString.read(from: &buf)
            )
        case 8: return .ServerConnection(
            message: try FfiConverterString.read(from: &buf)
            )
        case 9: return .Internal(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: BarkError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Network(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Database(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .InvalidMnemonic(message):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .InvalidAddress(message):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .InvalidInvoice(message):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .InsufficientFunds(message):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .NotFound(message):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .ServerConnection(message):
            writeInt(&buf, Int32(8))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Internal(message):
            writeInt(&buf, Int32(9))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBarkError_lift(_ buf: RustBuffer) throws -> BarkError {
    return try FfiConverterTypeBarkError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBarkError_lower(_ value: BarkError) -> RustBuffer {
    return FfiConverterTypeBarkError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Bitcoin network types
 */

public enum Network: Equatable, Hashable {
    
    case bitcoin
    case testnet
    case signet
    case regtest



}

#if compiler(>=6)
extension Network: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNetwork: FfiConverterRustBuffer {
    typealias SwiftType = Network

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Network {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .bitcoin
        
        case 2: return .testnet
        
        case 3: return .signet
        
        case 4: return .regtest
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Network, into buf: inout [UInt8]) {
        switch value {
        
        
        case .bitcoin:
            writeInt(&buf, Int32(1))
        
        
        case .testnet:
            writeInt(&buf, Int32(2))
        
        
        case .signet:
            writeInt(&buf, Int32(3))
        
        
        case .regtest:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNetwork_lift(_ buf: RustBuffer) throws -> Network {
    return try FfiConverterTypeNetwork.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNetwork_lower(_ value: Network) -> RustBuffer {
    return FfiConverterTypeNetwork.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt16: FfiConverterRustBuffer {
    typealias SwiftType = UInt16?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt16.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt16.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt32: FfiConverterRustBuffer {
    typealias SwiftType = UInt32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeArkInfo: FfiConverterRustBuffer {
    typealias SwiftType = ArkInfo?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeArkInfo.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeArkInfo.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeLightningReceiveStatus: FfiConverterRustBuffer {
    typealias SwiftType = [LightningReceiveStatus]

    public static func write(_ value: [LightningReceiveStatus], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeLightningReceiveStatus.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [LightningReceiveStatus] {
        let len: Int32 = try readInt(&buf)
        var seq = [LightningReceiveStatus]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeLightningReceiveStatus.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeLightningSendStatus: FfiConverterRustBuffer {
    typealias SwiftType = [LightningSendStatus]

    public static func write(_ value: [LightningSendStatus], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeLightningSendStatus.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [LightningSendStatus] {
        let len: Int32 = try readInt(&buf)
        var seq = [LightningSendStatus]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeLightningSendStatus.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeMovement: FfiConverterRustBuffer {
    typealias SwiftType = [Movement]

    public static func write(_ value: [Movement], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeMovement.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Movement] {
        let len: Int32 = try readInt(&buf)
        var seq = [Movement]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeMovement.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeVtxo: FfiConverterRustBuffer {
    typealias SwiftType = [Vtxo]

    public static func write(_ value: [Vtxo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeVtxo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Vtxo] {
        let len: Int32 = try readInt(&buf)
        var seq = [Vtxo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeVtxo.read(from: &buf))
        }
        return seq
    }
}
public func generateMnemonic()throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_func_generate_mnemonic($0
    )
})
}
public func validateArkAddress(address: String)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_func_validate_ark_address(
        FfiConverterString.lower(address),$0
    )
})
}
public func validateMnemonic(mnemonic: String)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeBarkError_lift) {
    uniffi_bark_ffi_fn_func_validate_mnemonic(
        FfiConverterString.lower(mnemonic),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_bark_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_bark_ffi_checksum_func_generate_mnemonic() != 49933) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_func_validate_ark_address() != 49932) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_func_validate_mnemonic() != 2707) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_all_vtxos() != 48937) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_ark_info() != 36948) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_balance() != 11221) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_bolt11_invoice() != 64551) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_claimable_lightning_receive_balance_sats() != 64974) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_config() != 57616) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_get_expiring_vtxos() != 19482) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_get_vtxo_by_id() != 41126) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_get_vtxos_to_refresh() != 55019) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_maintenance() != 9626) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_maintenance_refresh() != 29994) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_movements() != 23904) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_new_address() != 25174) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_new_address_with_index() != 52446) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_offboard_all() != 61123) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_offboard_vtxos() != 19001) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_pay_lightning_address() != 8340) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_pay_lightning_invoice() != 3587) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_peak_address() != 23469) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_pending_lightning_receives() != 7863) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_pending_lightning_sends() != 5489) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_properties() != 34715) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_refresh_vtxos() != 720) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_send_arkoor_payment() != 8472) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_send_round_onchain_payment() != 21156) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_spendable_vtxos() != 48976) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_sync() != 3312) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_try_claim_all_lightning_receives() != 53132) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_method_wallet_vtxos() != 16778) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_constructor_wallet_create() != 28953) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_bark_ffi_checksum_constructor_wallet_open() != 34910) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureBarkFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all